### ISSUE TITLE
Add support for Python 3.5

### ISSUE THREAD

**Issue by tweemeterjop** [giovino/fsi-dnsdb#8]
Please add support for Python 3.5.

The latest Python 3 from the Ubuntu 16.04 LTS repo is Python 3.5.2. This Ubuntu LTS still has 5 years of support :)

**Comment by giovino** [comment]
Let me look into it, off the top of my head I'm not sure if I did use any features that require Python 3.6

**Comment by giovino** [comment]
Upon further research... I am using the Python code formatter Black which has a requirement on Python 3.6. Given this requirement I will not be supporting Python 3.5. Sorry.
